#!/bin/bash
# This script updates everything in this folder for a backup
## Config files
cp /home/jackson/.vimrc /home/jackson/Documents/code/shell/conf/.vimrc
cp /home/jackson/.config/tmux/tmux.config /home/jackson/Documents/code/shell/conf/tmux.config
cp /home/jackson/.config/nvim/init.vim /home/jackson/Documents/code/shell/conf/nvim.init
cp /home/jackson/.bashrc /home/jackson/Documents/code/shell/conf/.bashrc

# Services Files
cp /etc/systemd/system/backup.service /home/jackson/Documents/code/shell/services/backup.service
cp /etc/systemd/system/monster.service /home/jackson/Documents/code/shell/services/monster.service

# Scripts
cp /usr/bin/backup /home/jackson/Documents/code/shell/shell/backup
cp /usr/bin/monster /home/jackson/Documents/code/shell/shell/monster
cp /usr/bin/moss /home/jackson/Documents/code/shell/shell/moss
cp /usr/bin/move /home/jackson/Documents/code/shell/shell/move
cp /usr/bin/backup_scripts /home/jackson/Documents/code/shell/shell/backup_scripts
cp /usr/bin/meow /home/jackson/Documents/code/shell/shell/meow

# Push to github
current_date=$(date +"%d-%m-%y-%H-%M")
cd /home/jackson/Documents//code/shell
git add .
git commit -m "auto update at $current_date"
git push
