#!/usr/bin/env bash
# This script updates everything in this folder for a backup
FILES="/home/jackson/Documents/Code/shell"

# Push to github
current_date=$(date +"%d-%m-%y-%H-%M")
cd $FILES
git add .
git commit -m "auto update at $current_date"
git push
