#!/usr/bin/env bash

current_date=$(date +"%d-%m-%y-%H-%M")

mount PARTUUID=3e7b1e43-ff1c-4813-b7f4-ad0bac43a72d /mnt/backup

if [ $? -ne 0 ]; then
	echo "Mount failed"
	exit 1
fi

echo -e "Mount Success\n"


backup_scripts # Updates the files in the github repo full of shell scripts and conf with the ones currently in use

echo -e "\nBackup started at $current_date\n"

exclude="--exclude */node_modules"

borg prune --force --force --stats --list --keep-within 2d -d 31 -w 8 -m 12 -y 2 --save-space /mnt/backup

borg create --progress --stats --show-rc --verbose --compression lz4  /mnt/backup::'{hostname}-{now}' /home/jackson/Documents

borg compact /mnt/backup

umount PARTUUID=3e7b1e43-ff1c-4813-b7f4-ad0bac43a72d


if [ $? -ne 0 ]; then
	echo "Unmount failed"
	exit 2
fi

echo -e "\nUnmount Success\n"

echo "Backup finished"
