#!/usr/bin/env bash

tmux new-session -d -s rice

tmux split-window -h

tmux split-window -v

tmux select-pane -t 1
tmux send-keys "cava" C-m
total_height=$(tmux display-message -p '#{window_height}')
new_height=$((total_height / 8))
tmux resize-pane -y $new_height

tmux select-pane -t 2
tmux send-keys "neofetch" C-m

tmux select-pane -t 0 
# Attach to the tmux session
tmux attach-session -t rice
